# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\anime_download\UI\config.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(670, 90)
        font = QtGui.QFont()
        font.setPointSize(16)
        Config.setFont(font)
        Config.setStyleSheet("QPushButton{\n"
"background-color:#dedede;\n"
"border-radius:6px\n"
"}\n"
"QPushButton:hover {\n"
"background-color:#aaaa7f;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#dedede;\n"
"color: #000000;\n"
"}")
        self.download_path_label = QtWidgets.QLabel(Config)
        self.download_path_label.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.download_path_label.setFont(font)
        self.download_path_label.setObjectName("download_path_label")
        self.download_path_lineEdit = QtWidgets.QLineEdit(Config)
        self.download_path_lineEdit.setGeometry(QtCore.QRect(120, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.download_path_lineEdit.setFont(font)
        self.download_path_lineEdit.setObjectName("download_path_lineEdit")
        self.browse_pushButton = QtWidgets.QPushButton(Config)
        self.browse_pushButton.setGeometry(QtCore.QRect(570, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.browse_pushButton.setFont(font)
        self.browse_pushButton.setStyleSheet("")
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.save_pushButton = QtWidgets.QPushButton(Config)
        self.save_pushButton.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(Config)
        self.cancel_pushButton.setGeometry(QtCore.QRect(570, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cancel_pushButton.setFont(font)
        self.cancel_pushButton.setObjectName("cancel_pushButton")

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "設定"))
        self.download_path_label.setText(_translate("Config", "下載路徑:"))
        self.browse_pushButton.setText(_translate("Config", "瀏覽"))
        self.save_pushButton.setText(_translate("Config", "儲存"))
        self.cancel_pushButton.setText(_translate("Config", "取消"))
