# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountLogin(object):
    def setupUi(self, AccountLogin):
        AccountLogin.setObjectName("AccountLogin")
        AccountLogin.setWindowModality(QtCore.Qt.ApplicationModal)
        AccountLogin.resize(320, 180)
        self.login_pushButton = QtWidgets.QPushButton(AccountLogin)
        self.login_pushButton.setGeometry(QtCore.QRect(80, 150, 75, 23))
        self.login_pushButton.setObjectName("login_pushButton")
        self.answer_label = QtWidgets.QLabel(AccountLogin)
        self.answer_label.setGeometry(QtCore.QRect(20, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_label.setFont(font)
        self.answer_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.answer_label.setObjectName("answer_label")
        self.question_label = QtWidgets.QLabel(AccountLogin)
        self.question_label.setGeometry(QtCore.QRect(0, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.question_label.setFont(font)
        self.question_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.question_label.setObjectName("question_label")
        self.password_label = QtWidgets.QLabel(AccountLogin)
        self.password_label.setGeometry(QtCore.QRect(20, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.password_label.setObjectName("password_label")
        self.account_comboBox = QtWidgets.QComboBox(AccountLogin)
        self.account_comboBox.setGeometry(QtCore.QRect(10, 10, 61, 22))
        self.account_comboBox.setObjectName("account_comboBox")
        self.question_comboBox = QtWidgets.QComboBox(AccountLogin)
        self.question_comboBox.setGeometry(QtCore.QRect(80, 70, 231, 21))
        self.question_comboBox.setObjectName("question_comboBox")
        self.answer_lineEdit = QtWidgets.QLineEdit(AccountLogin)
        self.answer_lineEdit.setEnabled(False)
        self.answer_lineEdit.setGeometry(QtCore.QRect(80, 100, 231, 21))
        self.answer_lineEdit.setObjectName("answer_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(AccountLogin)
        self.password_lineEdit.setGeometry(QtCore.QRect(80, 40, 231, 21))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.account_lineEdit = QtWidgets.QLineEdit(AccountLogin)
        self.account_lineEdit.setGeometry(QtCore.QRect(80, 10, 231, 21))
        self.account_lineEdit.setObjectName("account_lineEdit")
        self.remember_checkBox = QtWidgets.QCheckBox(AccountLogin)
        self.remember_checkBox.setGeometry(QtCore.QRect(80, 130, 151, 16))
        self.remember_checkBox.setObjectName("remember_checkBox")

        self.retranslateUi(AccountLogin)
        QtCore.QMetaObject.connectSlotsByName(AccountLogin)
        AccountLogin.setTabOrder(self.account_lineEdit, self.password_lineEdit)
        AccountLogin.setTabOrder(self.password_lineEdit, self.question_comboBox)
        AccountLogin.setTabOrder(self.question_comboBox, self.answer_lineEdit)
        AccountLogin.setTabOrder(self.answer_lineEdit, self.remember_checkBox)
        AccountLogin.setTabOrder(self.remember_checkBox, self.login_pushButton)
        AccountLogin.setTabOrder(self.login_pushButton, self.account_comboBox)

    def retranslateUi(self, AccountLogin):
        _translate = QtCore.QCoreApplication.translate
        AccountLogin.setWindowTitle(_translate("AccountLogin", "用戶登入"))
        self.login_pushButton.setText(_translate("AccountLogin", "登入"))
        self.answer_label.setText(_translate("AccountLogin", "答案:"))
        self.question_label.setText(_translate("AccountLogin", "安全提問:"))
        self.password_label.setText(_translate("AccountLogin", "密碼:"))
        self.remember_checkBox.setText(_translate("AccountLogin", "記住帳號密碼"))
