# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/myself_close.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyselfClose(object):
    def setupUi(self, MyselfClose):
        MyselfClose.setObjectName("MyselfClose")
        MyselfClose.resize(239, 146)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MyselfClose)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_label = QtWidgets.QLabel(MyselfClose)
        self.logo_label.setText("")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_2.addWidget(self.logo_label)
        self.message_label = QtWidgets.QLabel(MyselfClose)
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.verticalLayout_2.addWidget(self.message_label)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 9)

        self.retranslateUi(MyselfClose)
        QtCore.QMetaObject.connectSlotsByName(MyselfClose)

    def retranslateUi(self, MyselfClose):
        _translate = QtCore.QCoreApplication.translate
        MyselfClose.setWindowTitle(_translate("MyselfClose", "MyselfClose"))
        self.message_label.setText(_translate("MyselfClose", "儲存資料關閉中! 請稍等!"))
