# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\note.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Note(object):
    def setupUi(self, Note):
        Note.setObjectName("Note")
        Note.setWindowModality(QtCore.Qt.ApplicationModal)
        Note.resize(345, 200)
        self.note_label = QtWidgets.QLabel(Note)
        self.note_label.setGeometry(QtCore.QRect(10, 10, 341, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.note_label.setFont(font)
        self.note_label.setObjectName("note_label")
        self.confirm_pushButton = QtWidgets.QPushButton(Note)
        self.confirm_pushButton.setGeometry(QtCore.QRect(140, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirm_pushButton.setFont(font)
        self.confirm_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#dedede;\n"
"border-radius:6px\n"
"}\n"
"QPushButton:hover {\n"
"background-color:#aaaa7f;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#dedede;\n"
"color: #000000;\n"
"}")
        self.confirm_pushButton.setObjectName("confirm_pushButton")

        self.retranslateUi(Note)
        QtCore.QMetaObject.connectSlotsByName(Note)

    def retranslateUi(self, Note):
        _translate = QtCore.QCoreApplication.translate
        Note.setWindowTitle(_translate("Note", "注意事項"))
        self.note_label.setText(_translate("Note", "慢速: 1 次 1 個連接\n"
"一般: 1 次 3 個連接\n"
"高速: 1 次 8 個連接\n"
"星爆: 1 次 16 個連接\n"
"\n"
"連接值越高吃的網速就越多。\n"
"同時下載數量越高，記憶體與網速就吃越多。"))
        self.confirm_pushButton.setText(_translate("Note", "確定"))
