# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\save.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Save(object):
    def setupUi(self, Save):
        Save.setObjectName("Save")
        Save.setWindowModality(QtCore.Qt.WindowModal)
        Save.resize(217, 83)
        font = QtGui.QFont()
        font.setPointSize(12)
        Save.setFont(font)
        self.success_label = QtWidgets.QLabel(Save)
        self.success_label.setGeometry(QtCore.QRect(50, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success_label.setFont(font)
        self.success_label.setObjectName("success_label")
        self.confirm_pushButton = QtWidgets.QPushButton(Save)
        self.confirm_pushButton.setGeometry(QtCore.QRect(70, 50, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirm_pushButton.setFont(font)
        self.confirm_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#dedede;\n"
"border-radius:6px\n"
"}\n"
"QPushButton:hover {\n"
"background-color:#aaaa7f;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#dedede;\n"
"color: #000000;\n"
"}")
        self.confirm_pushButton.setObjectName("confirm_pushButton")

        self.retranslateUi(Save)
        QtCore.QMetaObject.connectSlotsByName(Save)

    def retranslateUi(self, Save):
        _translate = QtCore.QCoreApplication.translate
        Save.setWindowTitle(_translate("Save", "儲存成功"))
        self.success_label.setText(_translate("Save", "資料已成功儲存"))
        self.confirm_pushButton.setText(_translate("Save", "確定"))
