# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\url.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Url(object):
    def setupUi(self, Url):
        Url.setObjectName("Url")
        Url.resize(120, 80)
        self.url_error_label = QtWidgets.QLabel(Url)
        self.url_error_label.setGeometry(QtCore.QRect(25, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.url_error_label.setFont(font)
        self.url_error_label.setObjectName("url_error_label")
        self.url_error_pushButton = QtWidgets.QPushButton(Url)
        self.url_error_pushButton.setGeometry(QtCore.QRect(35, 45, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.url_error_pushButton.setFont(font)
        self.url_error_pushButton.setObjectName("url_error_pushButton")

        self.retranslateUi(Url)
        QtCore.QMetaObject.connectSlotsByName(Url)

    def retranslateUi(self, Url):
        _translate = QtCore.QCoreApplication.translate
        Url.setWindowTitle(_translate("Url", "錯誤"))
        self.url_error_label.setText(_translate("Url", "網址有誤！"))
        self.url_error_pushButton.setText(_translate("Url", "確定"))
